FROM node:alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install -g @angular/cli

RUN npm install

COPY . .

EXPOSE 4200

RUN chmod +x /usr/src/app/entrypoint.dev.sh
ENTRYPOINT [ "sh", "/usr/src/app/entrypoint.dev.sh" ]